/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Delete a password from the keyring for a given service and account. */
export declare function deletePassword(service: string, account: string): void

/** Get a password from the keyring for a given service and account. */
export declare function getPassword(service: string, account: string): string

/** Set a password in the keyring for a given service and account. */
export declare function setPassword(service: string, account: string, password: string): void
